apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: rdtrancoso/ecommerce-desafio-k8s:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
